---
- hosts: all 
  become: yes  
  become_method: sudo 

  tasks: 
  - name: install pythond-apt and apache2
    become: yes
    package:
      name:
        - python3-apt
        - apache2   
      state: latest

  - name: Copy apache with owner and permissions
    become: yes
    copy:
      src: files/config/apache2.conf
      dest: /etc/apache2/apache2.conf
      owner: root
      group: root
      mode: '0644'

  - name: Copy index  with owner and permissions
    become: yes
    copy:
      src: files/site/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'

  - name: Create a symbolic link
    become: yes
    file:
      src: /etc/apache2/mods-available/headers.load
      dest: /etc/apache2/mods-enabled/headers.load
      owner: corbyn915
      group: corbyn915
      state: link

  - name: Restart service , in all cases
    become: yes
    service:
      name: apache2
      state: restarted
